name: hive_todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.17.0
  animate_do: ^2.1.0
  panara_dialogs: ^0.1.2
  lottie: ^3.1.0
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  flutter_cupertino_date_picker_fork: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
